### ISSUE TITLE
React Version Issue

### ISSUE THREAD

**Issue by RagipSelcuk** [RagipSelcuk/dbcWidget#26]
**Cannot Update an unmounted root**
In updating the Master branch from the DbcChangeSave feature, React render could not resolve the given .dbc file location.

**To Reproduce**
1. Go to http://localhost:3000/
2. Click on DbcEditor
3. Scroll down to 'Open Dbc Raw File'
4. See the error in the terminal

**Expected behavior**
Could not open any page depending on the selected.dbc file

**Screenshots**
`
2024-08-06T03:19:41.000Z root ERROR Error: Cannot update an unmounted root.
    at ReactDOMHydrationRoot.render.ReactDOMRoot.render (http://localhost:3000/bundle.js:136518:11)
    at LocationListRenderer.render (http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-dialog_file-dialog-service_js.js:2755:23)
    at OpenFileDialog.onUpdateRequest (http://localhost:3000/vendors-node_modules_theia_filesystem_lib_browser_file-dialog_file-dialog-service_js.js:792:35)
    at __webpack_modules__.../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (http://localhost:3000/bundle.js:152429:22)
    at invokeHandler (http://localhost:3000/bundle.js:10917:21)
    at sendMessage (http://localhost:3000/bundle.js:10653:13)
    at runMessageLoop (http://localhost:3000/bundle.js:10967:17)
`

**Comment by RagipSelcuk** [comment]
it seems very similar with this issue [https://github.com/eclipse-theia/theia/pull/13454](https://github.com/eclipse-theia/theia/pull/13454)

**Comment by didarbilgin** [comment]
For me, when I click ‘Open Dbc Raw File’, I don’t get those errors. The file is created correctly, and the page depending on the newly created file opens just fine. But when I click ‘Open Dbc File’, like you mentioned, the page couldn’t open. However, the error I get is not what you described. I can retrieve the file directory info:

`[Info] 2024-08-08T09:38:49.189Z root INFO File dir – "file:///Users/didarnurbilgin/Desktop/CAN_DBC_EL9000B/EL9080-510B.dbc" (bundle.js, line 60234)`

But right after that, this is the error I get:

`[Error] Unhandled Promise Rejection: Error: A syntax error occurred on line 2 - Reason: Syntax Error at line 1:1. Expected one of  '[a-zA-Z_]+_'
	(anonymous function) (bundle.js:57776)`
	
Have you encountered this error before? I don’t think the error I’m getting is related to the React version or the syntax.

**Comment by RagipSelcuk** [comment]
Didar,

I have the same result for 'Open Dbc Raw File.' Unfortunately, I encountered the mentioned issue (OpenFileDialog.onUpdateRequest) after the merge operation. Could you please switch to the main branch and check the result again?

**Comment by RagipSelcuk** [comment]
The main issue is related to using the platform's general rules.
Proper usage should be as follows:
* #dbcWidget
* #yarn prepare
* #yarn start:browser

Please, fetch the main branch. If you have any failure, please don't hesitate to let me know.

**Comment by didarbilgin** [comment]
Thank you, I solved the problem. Apparently, the issue was caused by the changes I had made and not committed. When I reverted to the previous version and discarded the changes I made, the problem was resolved. Thank you for your help.
